import Head from 'next/head'
import Header from '../components/Header'
import Login from '../components/Login'
import { useSession, getSession } from "next-auth/react"

export default function Home({ userSession }) {
  if (!userSession) return <Login />;

  return (
    <div>
      <Head>
        <title>Facebook</title>
        {/* 
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> 
        */}
      </Head>

      <Header />

      <main>
        {/* Sidebar */}
        {/* Feed */}
        {/* Widgets */}
      </main>
    </div>
  )
}

// server side rendering
export async function getServerSideProps(context) {
  // get the user
  const session = await getSession(context);
  // console.log(session);

  return {
    props: {
      userSession: session,
    }
  }
}
