import Head from 'next/head'
import Header from '../components/Header'
import Login from '../components/Login'
import Sidebar from '../components/Sidebar'
import { getSession } from "next-auth/react"
import { useSession } from "next-auth/react"

export default function Home() {
  const { data: session } = useSession()

  if (!session) return <Login />;

  return (
    <div className='h-screen bg-gray-100 overflow-hidden'>
      <Head>
        <title>Facebook</title>
        {/* 
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> 
        */}
      </Head>

      <Header />

      <main className='flex'>
        <Sidebar />

        {/* Feed */}
        {/* Widgets */}
      </main>
    </div>
  )
}

// server side rendering
export async function getServerSideProps(context) {
  // get the user
  const session = await getSession(context);
  // console.log(session);

  return {
    props: {
      session
    }
  }
}
