import Head from 'next/head'
import Header from '../components/Header'
import Login from '../components/Login'
import Sidebar from '../components/Sidebar'
import Feed from '../components/Feed'
import Widgets from '../components/Widgets'
import { getSession } from "next-auth/react"
import { useSession } from "next-auth/react"
import { db } from '../firebase'
import { collection, query, getDocs, orderBy } from "firebase/firestore";

export default function Home({ posts }) {
  const { data: session } = useSession()

  if (!session) return <Login />;

  return (
    <div className='h-screen bg-gray-100 overflow-hidden'>
      <Head>
        <title>Facebook</title>
        {/* 
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> 
        */}
      </Head>

      <Header />

      <main className='flex'>
        <Sidebar />

        <Feed posts={posts} />

        <Widgets />
      </main>
    </div>
  )
}

// server side rendering
export async function getServerSideProps(context) {
  // get the user
  const session = await getSession(context);
  // console.log(session);

  // fetch posts on the server side
  const posts = await getDocs(query(collection(db, 'posts'), orderBy('timestamp', 'desc')));
  // console.log(posts);

  // when prefetch, ignore timestamp for now
  const docs = posts.docs.map(post => ({
    id: post.id,
    ...post.data(),
    timestamp: null
  }))
  // console.log(docs);

  return {
    props: {
      session,
      posts: docs,
    }
  }
}
